- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/upgrade.yml
    - include: tasks/repos.yml
    - include: tasks/packages.yml
    - include: tasks/snap.yml
    - include: tasks/user.yml
    - include: tasks/cron.yml
    - include: tasks/gnome.yml