- name: Install python-psutil package
  apt: name=python-psutil

- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/marco/.wallpaper.jpg owner=marco group=marco mode=600

- name: Set GNOME Wallpaper
  become_user: marco
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/marco/.wallpaper.jpg'"

- name: Copy lockscreenfile
  copy: src=files/lockscreen.jpg dest=/home/marco/.lockscreen.jpg owner=marco group=marco mode=600

- name: Set lock screen background
  become_user: marco
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/marco/.lockscreen.jpg'"

- name: Set GTK theme
  become_user: marco
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Numix'"

- name: Set icons theme
  become_user: marco
  dconf: key="/org/gnome/desktop/interface/icon-theme" value="'Numix-Circle'"

- name: Set cursor theme
  become_user: marco
  dconf: key="/org/gnome/desktop/interface/cursor-theme" value="'Whiteglass'"

- name: Set favourite application
  become_user: marco
#  dconf: key="/org/gnome/shell/favorite-apps" value="['firefox.desktop', 'org.gnome.Nautilus.desktop', 'thunderbird_thunderbird.desktop', 'franz.desktop', 'telegram-desktop_telegramdesktop.desktop', 'slack_slack.desktop', 'vscode_vscode.desktop', 'tusk_tusk.desktop', 'spotify_spotify.desktop']"
  dconf: key="/org/gnome/shell/favorite-apps" value="favorite-apps=['firefox.desktop', 'google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'thunderbird_thunderbird.desktop', 'franz.desktop', 'vscode_vscode.desktop', 'tusk_tusk.desktop', 'spotify_spotify.desktop']"

- name: Set correct dock icons' size
  become_user: marco
  dconf: key="/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size" value="'32'"

- name: Set dock to span on multiple monitors
  become_user: marco
  dconf: key="/org/gnome/shell/extensions/dash-to-dock/multi-monitor" value="'true'"

- name: Show date on clock
  become_user: marco
  dconf: key="/org/gnome/desktop/interface/clock-show-date" value="'true'"

- name: Show battery percentage
  become_user: marco
  dconf: key="/org/gnome/desktop/interface/show-battery-percentage" value="'true'"

