  - name: Install packages
    apt: name={{item}}
    with_items:
      - htop
      - mc
      - tmux
      - iotop
      - iftop
      - wireshark
      - terminator
      - unzip
      - zip
      - ubuntu-restricted-extras
      - vim
#      - timeshift
      - exfat-fuse
      - exfat-utils
      - python3-pip
      - adb
      - gnome-tweaks
      - numix-gtk-theme 
      - numix-icon-theme*
      - arc-theme