# install additional repositories

# download albert key
- name: Download albert key
  get_url:
        url: https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_18.10/Release.key 
        dest: /tmp/Release.key
# add albert key
- name: install albert key
  apt_key:
        file: /tmp/Release.key
        state: present


# install albert repo
- name: Install albert repository 
  apt_repository:
    repo: 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_18.10/ /'
    state: present
    filename: albert
    update_cache: yes